### ISSUE TITLE
Document colors not being remembered since new update

### ISSUE THREAD

**Issue by guylepage3** [andrewfiorillo/sketch-palettes#11]
Since the new Sketch 3.5 update, the document and global palettes can be changed but when I save and close the document, the palettes revert back to their original state. 

I've also tried clearing palettes and saving the documents but to no avail.

**Comment by andrewfiorillo** [comment]
Yeah, I saw this. Still trying to figure it out.

**Comment by bomberstudios** [comment]
Yay : )

**Comment by guylepage3** [comment]
Should this remain open until it's solved? It would be nice to receive an update. No?

**Comment by bomberstudios** [comment]
Well, it _is_ solved : )
