### ISSUE TITLE
Brand colors

### ISSUE THREAD

**Issue by i386** [andrewfiorillo/sketch-palettes#14]
I'd love it if there was some way to associate a palette with a set of brand colors. Change your brands primary color and see it update right across the Sketch file.

**Comment by andrewfiorillo** [comment]
I don't think that is within the scope of this plugin, but the <a href="https://github.com/getflourish/Sketch-Style-Inventory#user-content-select-layers-by-color-on-artboard">Style Inventory</a> plugin has a "Select Layers by Color" command that could help with what you are looking to do. It works on the selcted artboard, or the entire document.
