### ISSUE TITLE
Support transparency

### ISSUE THREAD

**Issue by cecileboucheron** [andrewfiorillo/sketch-palettes#16]
Great plugin (we've used it at Keybase!), but it looks like it doesn't support swatches with transparency.

**Comment by andrewfiorillo** [comment]
That's awesome you guys are finding it useful!

I have another issue open to <a href="https://github.com/andrewfiorillo/sketch-palettes/issues/5">support rgba colors</a>. I still need to decide on a new file format to implement that. But, it is planned.

**Comment by riddle** [comment]
Was very happy to have found this plugin but without alpha channel it’s a lot of work to re-apply transparency onto colors.

**Comment by andrewfiorillo** [comment]
@riddle this is in fact planned. But I have it covered in another issue: https://github.com/andrewfiorillo/sketch-palettes/issues/5

**Comment by andrewfiorillo** [comment]
@cecileboucheron Sketch Palettes now supports transparent colors.
