### ISSUE TITLE
Plugin doesn't have any options

### ISSUE THREAD

**Issue by blakeperdue** [andrewfiorillo/sketch-palettes#2]
I'm on Sketch Version 3.2.2 (9983). I'm not seeing any options for the plugin:

http://cl.ly/image/2U3g1711180O

**Comment by andrewfiorillo** [comment]
That screenshot doesn't seem to load for me. Do you mean it doesn't show up in the Plugins menu? Also, are you averse to updating to the latest version of Sketch?

**Comment by blakeperdue** [comment]
Try this link: https://dl.dropboxusercontent.com/u/1338834/share/Screen%20Shot%202015-09-24%20at%202.50.32%20PM.png

I'll ugprade to latest Sketch. That's probably it.
