### ISSUE TITLE
Document Pallets will not be saved within the doc

### ISSUE THREAD

**Issue by janjuno** [andrewfiorillo/sketch-palettes#21]
Please fix this, this is crucial. So when i load a pallete it will not be saved with the document i have always to reimport the palette. Since Sketch 3.8.2 the document palettes sometimes dissapears.

**Comment by andrewfiorillo** [comment]
Hi, I just tried and was not able to reproduce the bug. I loaded a palette into Document Colors, saved, then quit and reopened Sketch. They were still there.

Are you using the latest version of the plugin (1.3) ?

**Comment by megaroeny** [comment]
I was getting this too, but I updated to the latest version and it fixed it. Make sure you have the lastest version @jansemka. Should fix it

**Comment by janjuno** [comment]
I was updating after i recognized the behavior. maybe the update wasn't working at the time. But now i running 1.3. I will let you know when the bug appears again, let's see what happens.
