### ISSUE TITLE
Palette keeps disappearing on v3.8.3

### ISSUE THREAD

**Issue by saffad** [andrewfiorillo/sketch-palettes#23]
I keep encountering this issue on Sketch version 3.8.3. Unsure how to reproduce.

**Comment by andrewfiorillo** [comment]
Could you share some more details? Do you mean when you restart Sketch the palette you previously loaded is gone? Does this happen for Global Colors, Document Colors, or both?

**Comment by saffad** [comment]
Sorry.

Easy to reproduce:
1. Open sketch file
2. Load a palette in Document colors
3. Close sketch file (not quit)
4. Open the same sketch file
5. Palette is gone.

Hard to reproduce:
1. Open sketch file
2. Load a palette in Document colors
3. Designing going back and forth the palette
4. At some point the palette is gone. 

Other notes: It only happens to this one specific palette. The palette has a lot of colours (88).

**Comment by andrewfiorillo** [comment]
Thanks for the additional info! For the easy-to-reproduce scenario, are you
saving the document?

**Comment by saffad** [comment]
Not explicitly. Just closing the window. I assume this auto saves it?

**Comment by andrewfiorillo** [comment]
It does not (at least not always). You need to save the doc after loading colors into the Document Colors section of the color picker to ensure they persist the next time you open the document.

**Comment by saffad** [comment]
Ok. Makes sense. 

I checked my plugin version was 1.1. Inspected the `.sketchpalette` file and on the first line: `"compatibleVersion":"1.0","pluginVersion":"1.1"` I noticed i had an older version.

I uninstalled the plugin and installed 1.4. Created the palette again and haven't had the issue yet.
