### ISSUE TITLE
Importing multiple palettes

### ISSUE THREAD

**Issue by shanecarmody** [andrewfiorillo/sketch-palettes#24]
First, thank you for making the plugin. It’s very useful and I’m using it all the time to manage color schemes in Sketch.

I wanted to separate all the Material Design colors into their own respective `.sketchpalete` files so that I could select only the colors I need for each project (e.g. `material-design-red.sketchpalette`, `material-design-pink.sketchpalette`, etc.), rather than having all of the Material colors at once. 

However, it seems when I load a palette it overwrites the previous one. It seems it replaces the current palette with the new one. Is this a bug or just a use case that the plugin doesn’t handle?

**Comment by andrewfiorillo** [comment]
Glad you're finding the plugin useful. It currently does not supporting appending colors, but that could be a nice addition. I'll consider adding it.

**Comment by andrewfiorillo** [comment]
I just merged a pull request which changes the load functionality to append colors instead of replace them.
