### ISSUE TITLE
Not working on Version 3.8.2

### ISSUE THREAD

**Issue by Dinedinedine** [andrewfiorillo/sketch-palettes#27]
Hi there,
I have an issue with the plugin. I receive an error message saying "no colors in palette"
I let you check the screenshots below. Any thoughts on what it could be?
Cheers,
Amandine

![screen-shot-2016-07-21-at-17 39 54](https://cloud.githubusercontent.com/assets/20581987/17029369/43d94276-4f6b-11e6-85c1-bf305a155507.png)
![screen-shot-2016-07-21-at-17 39 55](https://cloud.githubusercontent.com/assets/20581987/17029368/43d6aef8-4f6b-11e6-91b5-cb7c693dd228.png)

**Comment by sambrucejoseph** [comment]
I have this problem too "No colors in palette" when i have a set of colours in palette.
Using Sketch 3.8.3

**Comment by andrewfiorillo** [comment]
Sketch 39 came out yesterday, and I updated the plugin to work with it. Try updating Sketch and this plugin and see if it still gives you problems.

**Comment by Dinedinedine** [comment]
@andrewfiorillo thanks a lot! It works now ;)
