### ISSUE TITLE
Not Saving on Sketch 39

### ISSUE THREAD

**Issue by rdm74** [andrewfiorillo/sketch-palettes#28]
When I go to save out a palette it acts normal but never actually saves the palette

**Comment by andrewfiorillo** [comment]
Which version of the plugin are you using? I just updated it yesterday to work with Sketch 39.

**Comment by rdm74** [comment]
Okay, thank you I downloaded it again and now it is working. I was using the one downloaded from sketch toolbox before.

**Comment by andrewfiorillo** [comment]
Great. Glad you got it working!
