### ISSUE TITLE
Crash when clearing palette while viewing color

### ISSUE THREAD

**Issue by vpanyushenko** [andrewfiorillo/sketch-palettes#29]
If you navigate to the color picker in Sketch, have a color selected, and then clear the palette, it causes Sketch to crash.

Exception Type:  SIGABRT
Exception Codes: #0 at 0x7fff84a6bf06
Crashed Thread:  0

Application Specific Information:
**\* Terminating app due to uncaught exception 'NSRangeException', reason: '**\* -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'

**Comment by andrewfiorillo** [comment]
I just gave that a shot and couldn't reproduce. Which version of Sketch and version of this plugin are you using?
