### ISSUE TITLE
Palettes not loading

### ISSUE THREAD

**Issue by ghost** [andrewfiorillo/sketch-palettes#31]
Ever since I updated to Version 39.1, palettes are not loading or clearing.

**Comment by Niknam** [comment]
Same here. Can't save palettes either.

**Comment by andrewfiorillo** [comment]
@ladyheatherly @Niknam I pushed a newer version of the plugin when Sketch 39.1 was released. If you haven't yet, can you give that a shot?

**Comment by Niknam** [comment]
@andrewfiorillo The new version works good! Sorry, my bad, should have checked if there was a new version out or not. Thanks a lot!

**Comment by andrewfiorillo** [comment]
No worries! I wish there were a more streamlined way of updating and being alerted of new versions of plugins.

**Comment by ghost** [comment]
That works. Thanks very much!
