### ISSUE TITLE
.sketchpalette file not saving

### ISSUE THREAD

**Issue by sreebala** [andrewfiorillo/sketch-palettes#32]
I am trying to save a document color palette. It shows the save menu, I enter a name to save the file but the template is not getting saved. When I go to the folder and check, I see there is no palette saved.

**Comment by andrewfiorillo** [comment]
I pushed a newer version of the plugin when Sketch 39.1 was released. If you haven't yet, can you give that a shot?

**Comment by sreebala** [comment]
I just updated the version and it worked. Thank you!
