### ISSUE TITLE
Issues Saving Document Palettes

### ISSUE THREAD

**Issue by guptamo** [andrewfiorillo/sketch-palettes#34]
I'm not sure if this is widespread, but I've been having issues saving document palettes. Specifically, I flat out can't.

I'm on Version 39.1 (31720) of Sketch. If you need any other info feel free to let me know.

**Comment by andrewfiorillo** [comment]
I checked, and I can't reproduce this issue. I released a new version of the plugin for the last Sketch update. If you haven' yet, can you give that a shot?

**Comment by guptamo** [comment]
Wasn't aware of the update. Seems to have fixed the issue!

Thanks for the reply 👍
