### ISSUE TITLE
change load functionality

### ISSUE THREAD

**Issue by guylepage3** [andrewfiorillo/sketch-palettes#35]
Currently, sketch-palettes, executes the following workflow when loading palettes.

>You can load colors into either the Global Colors section of the color picker or into the Document Colors section. Selecting "Load Palette..." from either menu will prompt you to open a .sketchpalette file containing the colors you want to load. This will replace whatever colors are currently in the selected section.

Which is fine but I would like to make a suggestion to change...
>This will replace whatever colors are currently in the selected section.

The reason being is that some clients have multiple palette sets.

**Request:**
It would be nice and, IMO a bit more intuitive, to execute the loading to only "add" to the current set instead of replacing the current set. If the user wants to replace, he/she would simply use the "clear" feature that is already built in.

**Comment by andrewfiorillo** [comment]
I just merged a pull request which changes the load functionality from replacing colors to appending them:
https://github.com/andrewfiorillo/sketch-palettes/pull/30
