### ISSUE TITLE
Stopped working in Version 41.2 (35397)

### ISSUE THREAD

**Issue by aaronmw** [andrewfiorillo/sketch-palettes#36]
It hasn't been moved to the "Deprecated" category by Sketch, but it doesn't actually load my palettes anymore :( I miss it dearly.

To clarify, I follow the same steps I always did: Sketch Palettes > Document Colors > Load palette... [choose my palette]

Before, it would add the colours to my file.

Now, it does nothing at all.

**Comment by andrewfiorillo** [comment]
Hmm, I'm not seeing the same thing. Could you check and make sure that you have the most recent version of the plugin? 
https://github.com/andrewfiorillo/sketch-palettes/releases/tag/1.5

Also, make sure you are not using an old palette. When I first released the plugin it used a file format that only worked with hex values. Soon after I released a version with a new file format that used rgba to support transparent colors. I maintained backwards compatibility as long as I could  until a recent Sketch release removed the functionality that relied on.

**Comment by aaronmw** [comment]
Ah, it's probably that latter case then. I made this palette quite awhile ago. I'll recreate it and see how that goes!

**Comment by aaronmw** [comment]
...Yup. Re-created the palette, opened a new document, loaded it, and they're all there.

Thanks Andrew :)

**Comment by andrewfiorillo** [comment]
No problem. Glad you got it working!

**Comment by guylepage3** [comment]
I also noticed that older versions of my saved palettes would not work with the new version of Sketch and had to manually recreate my global and document palettes. Just an FYI.

**Comment by andrewfiorillo** [comment]
@guylepage3 yeah, check out my above comment. The file format changed soon after the plugin was released, and I recently dropped backwards compatibility.

**Comment by guylepage3** [comment]
Might be a good idea to mention this on the README.md
