### ISSUE TITLE
Not loading palette

### ISSUE THREAD

**Issue by keano12** [andrewfiorillo/sketch-palettes#38]
I have had good luck with this plugin but I can't load a saved palette now for whatever reason. I can use other features like clear but not load.

**Comment by andrewfiorillo** [comment]
Sorry your having trouble! Are you using an old palette file? The format changed a while ago now to support transparent colors. I maintained backwards compatibility as long as I could, but a more recent Sketch update dropped the functionality I was relying on to do so.

You can see which version of palette file you're trying to load by opening the file in a text editor. The old version uses hex codes for colors, and the new one uses rgba.

**Comment by keano12** [comment]
ah ok makes sense. Thanks for the update. I will create a new palette and save.
thanks

> {"compatibleVersion":"1.0","pluginVersion":"1.1","colors":["#FFD400","#FFFFFF","#000000","#333333","#666666","#067AB4","#20A7D5","#F76C27","#70BE44","#C80000","#D41568","#999999","#B7B7B7","#CCCCCC","#DDDDDD","#E6E6E6","#EEEEEE","#F6F6F6","#54BBDE","#F06C69","#8ECCD7","#604C79","#77D4C2","#C0DC4C","#F6988B","#AB659F","#F5A91A","#72B24C"]}

**Comment by guylepage3** [comment]
This should be more transparent. Took me a bit to figure this out my old files were no longer supported with newer versions of sketch

**Comment by andrewfiorillo** [comment]
Good call. I merged your request (with some additional explanation) to detail the issue in the README. Thanks!
