### ISSUE TITLE
Name colors

### ISSUE THREAD

**Issue by MDBas** [andrewfiorillo/sketch-palettes#41]
Hi,

It would really help us if we could name the colors in the palette.
I'd like to know if this is something you see as an enhancement too.

Thanks,
Bas

**Comment by andrewfiorillo** [comment]
I would really love to do this, and it is frequently requested. But it is nowhere near trivial or straightforward to build, and would require writing a plugin many times more complex than the current one. It would need to be able to store data in different way than is currently used by Sketch presets, in both a global and per-document implementation.  It would also need to change the UI of Sketch itself to display the names of color presets, and would obviously need an an interface for actually naming them. My hope is that folks at Sketch add the ability to name presets natively, and I can just store that information in the in addition to the color values currently stored in the palette file. Unless they add that, I think it is outside the scope of this plugin.

**Comment by andrewfiorillo** [comment]
Good news! In the forthcoming Sketch 53 release, support for naming presets will be added. So I will then be able to add the ability to save preset names with a palette. I'll be tracking it in this issue: https://github.com/andrewfiorillo/sketch-palettes/issues/74
