### ISSUE TITLE
[Feature Request] Integrate with Sketchpacks Relay to serve auto-updates

### ISSUE THREAD

**Issue by adamkirkwood** [andrewfiorillo/sketch-palettes#46]
More details found @ https://github.com/integration/sketchpacks-relay

Example
![screen shot 2017-03-22 at 4 08 57 pm](https://cloud.githubusercontent.com/assets/52746/24224720/fc40de64-0f19-11e7-8473-a2798193fc33.png)

**Comment by andrewfiorillo** [comment]
It looks like this plugin is already present in Sketchpacks. Is there additional integration required?
