### ISSUE TITLE
Can't load .sketchpalette file.

### ISSUE THREAD

**Issue by b-d-m-p** [andrewfiorillo/sketch-palettes#47]
Hi, 

Thank you for the great plugin. 

I can't load this .sketchpalette. http://cl.ly/2k1g3h1w1c1y

I don't see a change after selecting it to load. 

Am I doing something wrong?

Cheers

**Comment by AnnaGalante** [comment]
I also have the same issue, same palette.

**Comment by andrewfiorillo** [comment]
Ok, I was able to reproduce the issue with your palette. I'm going to investigate further. Hopefully will have it resolved sometime soon.

**Comment by dhniels** [comment]
Opened sketch today for the first time in a month probably and noticed my custom palettes weren't loading either.

**Comment by andrewfiorillo** [comment]
I just pushed a release which should fix this issue. It was an older palette format, and backwards compatibility for older files was busted. Let me know if that doesn't do the trick though.

**Comment by dhniels** [comment]
Awesome man, just realized I was on the older version - couldn't remember if sketch updated plugins or if you had to do it manually haha. Working now on latest.

**Comment by andrewfiorillo** [comment]
Right on. Sketch doesn't currently update plugins, but the great news is that it is actually a feature that is being added in a forthcoming Sketch release. So, you can look forward to not having to worry about issues like this in the future.

**Comment by sk1ppah** [comment]
I'm having some problems adding an existing Sketch palette into my new colleague's Sketch (both are v. 51.2). Here's what's happening:

- When we go to Plugins > Sketch Palettes, hers (the broken one) has an extra submenu with Document Colors and Global Colors in it (mine, the working one, goes straight to Load/Save/Clear Palette)
- When we try to Load a palette on hers, the file explorer window never pops up
- When she tries to export an exported .sketchpalette file, Sketch is grayed out in the list of applications as being unable to open it. 

Have tried uninstalling/reinstalling the plugin, making sure Sketch is fully updated etc, but no luck.

**Comment by andrewfiorillo** [comment]
It sounds like your colleague might have an older version of the plugin installed. Previous versions had multiple menu commends, until later improvement allowed for moving those options into the dialog that appears after loading a palette.

**Comment by sk1ppah** [comment]
That worked! Turns out the file she uninstalled / reinstalled to was an old one she had downloaded a while ago. Now we're rolling - thanks!

**Comment by yingyingzux** [comment]
I experienced this issue of not being able to load color sketch palettes today today. I just downloaded the plugin and running sketch v66.1. Please help, thank you.
