### ISSUE TITLE
Updatable Colors

### ISSUE THREAD

**Issue by timohofmeijer** [andrewfiorillo/sketch-palettes#50]
I have long longed for a way start out with some palette and iterate on it while designing. To immediately see the effects of a color change in the overall design, allowing for more refined color choices and also for defining color themes. Similar to the way css variables work, or how print design applications works (Adobe now calls it global-colors). I’d love to help!

**Comment by guylepage3** [comment]
+1 for default global colors. Could simply start out with the 500 base colors from material design. 

https://material.io/guidelines/style/color.html#color-color-tool

**Comment by andrewfiorillo** [comment]
@timohofmeijer that sounds like a really useful tool. How are you imagining this functionality would interact with the Sketch Palettes plugin?

**Comment by timohofmeijer** [comment]
Illustrator lets you change a regular swatch into a global swatch. When changing a global swatch color, all occurrences change with it. I'm afraid this can't be done within the native sketch swatch/picker solution which makes it quite a complex project, and perhaps beyond the scope of the `sketch-pallets` plugin. A native solution would be much preferred for something this fundamental of course 😊

**Comment by olafchou** [comment]
couldn't load color palette

**Comment by pipifix** [comment]
like olafchou, i'm not able to load palettes. the system dialog for openng files is not showing up. macOS High Sierra, Sketch 48.2, sketch-paletes latest master. thanks for help

**Comment by andrewfiorillo** [comment]
@timohofmeijer after thinking about this some more, I think it is out of the scope of this plugin. I agree it would be super useful functionality though. If Sketch added the functionality, I'd happily make whatever changes would be needed the for the plugin to support it.
