### ISSUE TITLE
Saving doesn't work in Sketch 45.1

### ISSUE THREAD

**Issue by Oli4k** [andrewfiorillo/sketch-palettes#51]
Saving a palette from document colors does not bring up the saving dialog. From the global colors menu it does but no palette file is saved in both cases.
<img width="1187" alt="schermafbeelding 2017-07-06 om 11 27 03" src="https://user-images.githubusercontent.com/7113659/27904765-124206da-623e-11e7-9337-5f681f8abc1d.png">

**Comment by andrewfiorillo** [comment]
Hey, I just tried with the newest update of Sketch, 45.1, and I'm not able to reproduce the issue. Are you using the latest version of the Sketch Palettes Plugin?
https://github.com/andrewfiorillo/sketch-palettes/releases/latest

Note: the recent Sketch release just added functionality for auto-updating plugins, which is awesome. There is another GitHub issue for adding support for that. I hope to have that done soon.
