### ISSUE TITLE
Sketch Palettes not working on Sketch 46.1

### ISSUE THREAD

**Issue by PedrosPod** [andrewfiorillo/sketch-palettes#52]
The plugin is no longer working on this version of Sketch. Clicking Load Palette does nothing. I tried re-installing everything but still, i can't load any palette since no Browse windows pop up.

Thank you,
Pedro

**Comment by andrewfiorillo** [comment]
Hello. I'm not able to reproduce your issue in sketch 46.1.

Also, I just pushed a [change](https://github.com/andrewfiorillo/sketch-palettes/releases/tag/2.11) to support plugin updating within Sketch. You might want to go ahead and grab that anyway, so you don't have to go to GitHub to get the latest version. I don't think anything has changed that would affect plugin loading, but can you download that first, and then try provide any steps to reproduce or additional clues?

**Comment by PedrosPod** [comment]
The Save Palette Works, the Clear Palette works ... the Load Palette doesn't. I just updated the plugin to the 2.11 as your information.

I can't seem to figure out why this happens since no error shows.

**Comment by andrewfiorillo** [comment]
Is there anything else you can share about your setup? What version of macOS are you running? What other plugins do you have installed?

**Comment by andrewfiorillo** [comment]
And if possible, maybe you could provide a screencap? Either video or just a gif, using something [likelicEcap](https://www.cockos.com/licecap/)?

**Comment by PedrosPod** [comment]
Here the specs:

- macOS High Sierrra ( 10.13 Beta )
- Macbook Pro 2016
- Sketch 46.1
- Sketch Palettes 2.11

And here's the capture:

![sketch_palette_issue](https://user-images.githubusercontent.com/8738177/29131761-cc84d386-7d25-11e7-93d3-efe2383b6c7b.gif)

Sorry for the quality though.
