### ISSUE TITLE
Can't load palettes on Sketch 47

### ISSUE THREAD

**Issue by careylin** [andrewfiorillo/sketch-palettes#55]
Came across this plugin recently and found an issue with loading palettes. Clearing and saving the palette works but when trying to load that same saved palette back in it fails. I repro'd 47 and 47.1 and both have this issue. I tried it out on 46.2 and loading back in works so it seems they have yet again changed some palette code. 😞

**Comment by andrewfiorillo** [comment]
Thanks for the heads up. I'll check it out.

**Comment by andrewfiorillo** [comment]
Ok, I just pushed a fix for this:
https://github.com/andrewfiorillo/sketch-palettes/releases/tag/2.13

Let me know if you still have any trouble!
