### ISSUE TITLE
No .sketchplugin file

### ISSUE THREAD

**Issue by raybesiga** [andrewfiorillo/sketch-palettes#56]
In the installation README, it mentions the following:

"Move the Sketch Palettes plugin into your Plugins folder or double-click the .sketchplugin file."

However, when I browse the code, I cannot find the .sketchplugin file. Is it missing or am I looking in the wrong place? 

Thanks for your incredible work.

**Comment by andrewfiorillo** [comment]
Hello!

The .sketchplugin file is essentially a folder itself, with a different file extension. All the plugin code lives inside of it. If you cloned or downloaded the repository from GitHub, it should be located in the top level of the repository:

sketch-palettes/Sketch Palettes.sketchplugin/

Does that answer your question?

**Comment by raybesiga** [comment]
Yes, it does. Thank you.
