### ISSUE TITLE
Unable to load palette

### ISSUE THREAD

**Issue by designtothrive** [andrewfiorillo/sketch-palettes#58]
Sketch Version 48.2 
Plugin is updated to version 2.0 
macOS High Sierra version 10.13.2

I am able to "Save" a palette and "Clear" a palette but unable to "Load" an existing palette. When I select "Load Palette" absolutely nothing happens. I have tested the option to save and clear and both are working just fine. 

I love this plugin! Thank you for creating it. :) It was working like a champ. I think it's related to updating Sketch?

**Comment by andrewfiorillo** [comment]
Hi! Glad you're finding the plugin useful. I just tried to reproduce your issue, but was unable. You said your plugin was updated to version 2.0. I pushed a newer version (2.13) when a bug was introduced in Sketch 47, which I think is the issue you are experiencing. If you haven't yet, give the latest version a shot:
https://github.com/andrewfiorillo/sketch-palettes/releases/tag/2.13

if that doesn't do the trick, let me know!

**Comment by mikescopino** [comment]
Thank you for this fast answer Andrew. I was experiencing the same issue and 2.13 resolved it. FYI, for those that need it, the version number is listed in the Manage Plugins window of Sketch. I never assumed I was out of date but was actually running 1.5.
