### ISSUE TITLE
Can't load palettes

### ISSUE THREAD

**Issue by hellohynes** [andrewfiorillo/sketch-palettes#59]
I am unable to load palettes in Sketch 48.2. I can clear and save palettes, but I am unable to load one. When I attempt to load one it seems to fail silently.

**Comment by andrewfiorillo** [comment]
I tried, and I'm unable to reproduce the issue. The most recent version of the plugin fixed a loading bug which was introduced in Sketch v47. If you haven't yet, make sure you are running the latest version:
https://github.com/andrewfiorillo/sketch-palettes/releases/tag/2.13

If that doesn't do the trick, any steps to reproduce, and a test file which fails to load would be helpful to troubleshoot.

**Comment by hellohynes** [comment]
I think something was up with my plugin. I removed the plugin, reinstalled it, and everything works fine now. Sorry for the false alarm.

**Comment by andrewfiorillo** [comment]
No worries!
