### ISSUE TITLE
Can't Load Palettes in 49.1

### ISSUE THREAD

**Issue by janedepgen** [andrewfiorillo/sketch-palettes#63]
Since updating to 49.1, when you click Load Palette nothing pops up to select a palette so I can't get any new palettes.

**Comment by andrewfiorillo** [comment]
I just pushed a new version which should ix this issue. You can update it in Sketch or grab it from the link below. Let me know if you still have any issues!

https://github.com/andrewfiorillo/sketch-palettes/releases/latest
