### ISSUE TITLE
README says it has version #, does not

### ISSUE THREAD

**Issue by ahainen** [andrewfiorillo/sketch-palettes#65]
Hi - cleaning out my Sketch plugins as I'm running into performance issues. Version number is stated to be in the README, but is not. (My local version is 2.14, I was trying to see if 2.14 was the most recent)

![image](https://user-images.githubusercontent.com/972868/40314691-417e81cc-5ce7-11e8-8787-970d79218ee5.png)

**Comment by andrewfiorillo** [comment]
Hello. I'm not sure I understand the issue. It appears to show the correct lest version in the plugins menu screenshot you shared. 2.14 is still the latest release. Is there something missing?
