### ISSUE TITLE
[bug report] After reopening Sketch global palettes resets to basic

### ISSUE THREAD

**Issue by lyapustin** [andrewfiorillo/sketch-palettes#66]
**My steps:**
1. Clear palettes > Global (all marks).
2. Load palettes > from file in Dropbox, applied to Global (all marks).
3. Works fine.
…
4. Close Sketch, open again.
5. All Global palettes are the same as before 1st step.

Repeats every time. Any ideas? Thanks in advance!

Sketch 48.2, Mac OS Sierra 10.12.6.

**Comment by andrewfiorillo** [comment]
Hello!
I tried those steps, and was unable to reproduce the bug on the latest version of Sketch, version 50.2. It looks like you are running an older version, 48.2. Try giving the latest version of Sketch  a shot (and the [latest version](https://github.com/andrewfiorillo/sketch-palettes/releases/latest) of  Sketch Palettes if that's not up to date as well), and let me know if you're still experiencing the issue.
