### ISSUE TITLE
system window to load palettes is not opening

### ISSUE THREAD

**Issue by pipifix** [andrewfiorillo/sketch-palettes#67]
On macOs 10.13.5 / Sketch 50.2 (55047) i'm not able to load (allready saved) palletes in a new sketch file. Everytime i try, i see a short flickering (of the window?) but the system dialog is not shown. Saving palletes is working correctly.

**Comment by andrewfiorillo** [comment]
Sorry you're having issues. I'm not about to reproduce the bug. Are you using the latest version of the plugin? https://github.com/andrewfiorillo/sketch-palettes/releases/latest
