### ISSUE TITLE
Unable to load saved color palettes file

### ISSUE THREAD

**Issue by sonaliagrawal** [andrewfiorillo/sketch-palettes#68]
Running Sketch 51 and I use Sketch Palettes plugin to save document colors. The save option works, but when I click on Load Palette..., it doesn't seem to do anything. Please help!

**Comment by andrewfiorillo** [comment]
Hello! I tested and can't reproduce the bug. Are you using the latest version of the plugin?
https://github.com/andrewfiorillo/sketch-palettes/releases/latest

**Comment by sonaliagrawal** [comment]
Ah...that is it..I thought I'll get an plugin update notification in sketch itself. Installed the latest and now it's working! Thank you so much @andrewfiorillo 👍

**Comment by andrewfiorillo** [comment]
Sorry it didn't notify you. Someone else mentioned that they didn't get notified as well, so I'll look into that. But I'm glad updating worked!
