### ISSUE TITLE
Can't load a saved palette

### ISSUE THREAD

**Issue by cmcmo** [andrewfiorillo/sketch-palettes#72]
I have installed the plugin, and am trying to load a saved palette created by a teammate. I get no error message, but nothing happens as far as I can tell. I deleted all my global colors previously, thinking this would replace them, but now there is nothing :( 

I was in Sketch 51, but it wasn't working, so now I updated to Sketch 52, and it's still not working. Is anyone else having issues? Is there something I can try? I tried installing the plugin again, and restarting Sketch, to no avail.

**Comment by andrewfiorillo** [comment]
I just tried, and am unable to reproduce the issue. Would you be able to share the palette you are trying to load?

**Comment by cmcmo** [comment]
Of course, can I send it to you privately?

**Comment by andrewfiorillo** [comment]
you can send it here: andrewjfiorillo@gmail.com
