### ISSUE TITLE
Sketch v52.2 doesn't work

### ISSUE THREAD

**Issue by Jeason0228** [andrewfiorillo/sketch-palettes#73]
can save &export color,but i can't load a sketchpalette
when i pick up the .sketchpalette.there is no any windows to show me next step

**Comment by Jeason0228** [comment]
@andrewfiorillo here?

**Comment by andrewfiorillo** [comment]
I just tested, and am unable to reproduce your issue. A few things to try:

1. Make sure you are using the latest version of both Sketch and the Sketch Palettes plugin.
2. Check that you are not using a palette created prior to June 20, 2016, when the file format changed.
3. If you can, try saving a new palette from Sketch using the plugin, and then loading that one.

If none of those do the trick, if you could share the palette file, I can try to reproduce the issue with that file.

**Comment by bryancostanich** [comment]
I'm seeing the same issue in v52.5. Attached is my color palette.
[WildernessLabs.sketchpalette.zip](https://github.com/andrewfiorillo/sketch-palettes/files/2665829/WildernessLabs.sketchpalette.zip)
