### ISSUE TITLE
In Sketch 53.2 color names are null

### ISSUE THREAD

**Issue by NSemakov** [andrewfiorillo/sketch-palettes#83]
Hi.
In Sketch 53 (72520) all exported colors have proper names
{"name":"vendor_color_01","red":0.9372549019607843,"green":0.9372549019607843,"blue":0.9568627450980391,"alpha":1}

but in Sketch 53.2 (72643) same color become to
{"name": null,"red":0.9372549019607843,"green":0.9372549019607843,"blue":0.9568627450980391,"alpha":1}

**Comment by andrewfiorillo** [comment]
Hello, and thanks for spotting this. I'm able to reproduce and it appears to happen for global presets only. Hopefully will have a fix soon.

**Comment by andrewfiorillo** [comment]
Actually I take that back. I can't reproduce. Are you sure you've named the color in Sketch? It will print null into the palette if it is not named. Though colors with a null name value in the .sketchpalette file in will still display the hex value in Sketch once imported.
