### ISSUE TITLE
Unable to save palette with Sketch 55.1

### ISSUE THREAD

**Issue by ttseng** [andrewfiorillo/sketch-palettes#85]
Updated to the latest version of Sketch (55.1) and am unable to save palettes - clicking Save Palette does not launch the usual dialog for selecting what to export.

**Comment by GAL323-ui** [comment]
I'm having the same issue.

**Comment by andrewfiorillo** [comment]
Thanks for the heads up. I'll check it out!

**Comment by andrewfiorillo** [comment]
I just checked it out, and I'm unable to reproduce the problem. Are you using the latest version of the plugin?
