### ISSUE TITLE
Sketch Palettes not working on Sketch 56.3

### ISSUE THREAD

**Issue by heidi-lilly** [andrewfiorillo/sketch-palettes#88]
Nothing happens when trying to save/load/clear palette with the latest Sketch update.

Sketch 56.3 | MacOS Mojave 10.14.6

**Comment by andrewfiorillo** [comment]
I just checked it out, and I was not able to reproduce the issue. Could you double-check you are using the latest version of the plugin? And if so, and you still have the issue, could you share the palette you are trying to load so I can see if that helps me reproduce the bug?

**Comment by heidi-lilly** [comment]
Hi @andrewfiorillo — I uninstalled and reinstalled and the problem went away. My apologies!!
