### ISSUE TITLE
Sketch-palettes is not working after updated masOS Catalina

### ISSUE THREAD

**Issue by linpeiyings** [andrewfiorillo/sketch-palettes#89]
After updated macOS Catalina, the color palette is missing when open a new sketch file, only worked in old files.
I have tried the latest version of plug-in and to load palette again, but it didn't work.

Sketch version 56.3 | macOS Catalina 10.15

**Comment by AriesDesign** [comment]
I had this issue a few months back as well, but just tried it again on a new computer and so far it works like it did before.

Sketch v 63.1  |. macOS Catalina 10.15.3

**Comment by pmclough** [comment]
Same issue, plugin stopped working after setting up and installing Sketch on my new laptop. When I try to load a new palette nothing happens. Have tried the latest version and past versions of the plugin, but nothing has worked just yet. 

Sketch v 63.1 | macOS Catalina 10.15.3

**Comment by andrewfiorillo** [comment]
I'm not able to reproduce using  Sketch v 63.1 / macOS Catalina 10.15, which is the combo mentioned first. I can try updating from Catalina 10.15 to 10.15.3 to see if that reproduces it. 

But one more thing to check on your ends—are you using an old palette file? Early on when the plugin was first released, the file format was different, and subsequently to support new features, that format could no longer be supported. Try saving a new palette from Sketch and then loading that one.

**Comment by pmclough** [comment]
Looks like it was an issue with the palette file. Was able to load a new palette with no issues. Thanks!
