### ISSUE TITLE
Include palettes in package

### ISSUE THREAD

**Issue by JesseBilsten** [andrewfiorillo/sketch-palettes#9]
If a user overwrites their default color palette they can set it back to the defaults in Sketch.

https://www.dropbox.com/s/0br2a8dba6fjzni/Default.sketchpalette?dl=0

**Comment by andrewfiorillo** [comment]
I'm trying to be really judicious about what I add to the menu. Do you think it is common that people want to get back to that default set? You could also imagine, alternatively, replacing the "clear palette" command with "reset palette" command.

**Comment by JesseBilsten** [comment]
I think adding "reset" or back to defaults works and appreciate the
judicious nature of adding something to the menu. I could imagine someone
being upset after they spent a lot of time setting up a palette and then
couldn't get back to it.

**Comment by andrewfiorillo** [comment]
Well, if someone loads a new palette, I'm not sure we could get back a previous palette that was never saved (unless that temporary unsaved palette data was somehow being autosaved somewhere). But we _could_ reset to a hard-coded default set. I was thinking more about problem of inadvertently overwriting your palette though. Perhaps a double confirm or option to append is the solution there.

**Comment by JesseBilsten** [comment]
An MVP solution would be to provide a link in the README to the Default
palette hosted as a gist:
https://gist.github.com/JesseBilsten/f182bb124ad58278156d

I moved mine from the Dropbox link there so it's easier to link to/maintain.

**Comment by bzx** [comment]
+1 for adding an option to reset to a default color palette - this is what I wanted to do immediately after clearing the colors and noticing that I can't revert it back in any new document.

**Comment by andrewfiorillo** [comment]
I didn't add an option to the menu, but I've bundled some palettes with the plugin now, and included the default Sketch palette.
